spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/elib
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace    # ??? ???? ?? ???? ??? ? ??.

#server:
#  port : 8080